### ISSUE TITLE
Link to this repository from the SAPUI5 Documentation

### ISSUE THREAD

**Issue by gregorwolf** [SAP/ui5-manifest#13]
Hello ui5-manifest Maintainers,

could you please reach out to the SAPUI5 Documentaiton team and get a link to this repository included in the documentation for "Descriptor for Applications, Components, and Libraries" which is available at:

- https://help.sap.com/viewer/468a97775123488ab3345a0c48cadd8f/202009.000/en-US/be0cf40f61184b358b5faedaec98b2da.html
and
- https://sapui5.hana.ondemand.com/#/topic/be0cf40f61184b358b5faedaec98b2da

?

That would help a lot to find this repository and add it to the VS Code Configuration to get the input help.

Best regards
Gregor

**Comment by silkearians** [comment]
Thanks a lot for the suggestion, I will get in touch with the colleagues responsible for the documentation.

Best regards
Silke

**Comment by SabineLoss** [comment]
We will add the link to the topics. Thanks for suggesting it. If you want to reach us (UI5 documentation team) directly, you can also add suggestions for documentation improvements in the https://github.com/SAP/openui5-docs repository. 

Best regards,
Sabine

**Comment by silkearians** [comment]
Hi Gregor,

this is done now in latest UI5 docu, e.g. https://sapui5.hana.ondemand.com/#/topic/be0cf40f61184b358b5faedaec98b2da -> Descriptor Schema
Therefore I am closing the issue.

Thanks again for the hint and best regards
Silke

**Comment by gregorwolf** [comment]
Thank you.
