### ISSUE TITLE
Update `ui5-manifest` for the SAPUI5 1.89

### ISSUE THREAD

**Issue by pubmikeb** [SAP/ui5-manifest#17]
SAPUI5 has been updated to 1.89 ([here](https://ui5.sap.com/1.89.0/) and [here](https://openui5.org/releases/)) but the [`ui5-manifest`](https://github.com/SAP/ui5-manifest) hasn't been yet updated.

**Comment by silkearians** [comment]
This is correct. Reason is that there are no new attributes for UI5 1.89 and we only create new manifest version if there is a new attribute. We had introduced a https://github.com/SAP/ui5-manifest/blob/master/mapping.json for the mapping of UI5 and manifest version.

**Comment by pubmikeb** [comment]
Great, thanks for the clarification.
