### ISSUE TITLE
JSON Schemastore holds outdated definition

### ISSUE THREAD

**Issue by BenReim** [SAP/ui5-manifest#18]
**Issue**
The schema that is available at https://json.schemastore.org/ui5-manifest.json does not reflect the latest schema version.

**Sample manifest entry**
```json
{
    "sap.app": {
        "type": "card"
    }
}
```

**Validation Error**
`Value is not accepted. Valid values: "application", "component", "library".`

**Comment by silkearians** [comment]
Please use [UI5-Manifest](https://raw.githubusercontent.com/SAP/ui5-manifest/master/schema.json) as this links to our repo.
The [json.schemastore.org/ui5-manifest.json](https://json.schemastore.org/ui5-manifest.json) has not been added by SAP, we tried to contact the owner @kyakubi as we meanwhile have the SAP provided schema but so far without a response.

**Comment by silkearians** [comment]
We requested removal from JSON schema store for old outdated schema which is not owned by SAP: see https://github.com/SchemaStore/schemastore/pull/1599
