### ISSUE TITLE
Schema for fioriSandboxConfig.json

### ISSUE THREAD

**Issue by gregorwolf** [SAP/ui5-manifest#19]
Hello UI5 Manifest Team,

is there any chance to also get a schema for the fioriSandboxConfig.json file?

Best Regards
Gregor

**Comment by silkearians** [comment]
Hi Gregor,

I'll forward your request to the SAP Fiori launchpad colleagues.

Best regards
Silke

**Comment by gregorwolf** [comment]
Is there a repository where this is tracked or should I create an SAP incident to track this?

**Comment by silkearians** [comment]
Hi Gregor,

I got the following information from FLP experts:
As this is a feature request please create one as described under https://launchpad.support.sap.com/#/notes/2469897.

Thanks in advance and best regards
Silke
