### ISSUE TITLE
"sap.ui5/rootView" doesn't propose an "async" property

### ISSUE THREAD

**Issue by pubmikeb** [SAP/ui5-manifest#6]
`sap.ui5/rootView` doesn't propose an `async` property in 1.23.0 schema.

Is it a bug or `sap.ui5/rootView/async` has been deprecated?

According to the following articles, `sap.ui5/rootView/async` is still supported:
* https://sapui5.hana.ondemand.com/#/topic/493a15aa978d4fe9a67ea9407166eb01
* https://sapui5.hana.ondemand.com/#/topic/408b40efed3c416681e1bd8cdd8910d4.html

**Comment by petermuessig** [comment]
Hi @pubmikeb,

this seems to be a bug in the schema the `sap.ui5/rootView` allows additionalProperties, but indeed the `async` property is not maintained. This will be possible to be extended...

THX and best regards,
Peter

**Comment by pubmikeb** [comment]
Hi @petermuessig,
is there any roadmap for fixing this ticket?

**Comment by petermuessig** [comment]
Hi @pubmikeb ,

Big Sorry for the long delay! I will follow up on this next Monday with the responsible developers. 

Best regards,
Peter

**Comment by pubmikeb** [comment]
@petermuessig, thanks for the extremely fast response!

It would be great if the dev team could also have a look on https://github.com/SAP/ui5-manifest/issues/5 and https://github.com/SAP/ui5-manifest/issues/9 as well.

**Comment by petermuessig** [comment]
@pubmikeb - we will fix this issue here and provide it as part of the next release of the manifest schema `1.27.0` in about 2 weeks from now.

**Comment by pubmikeb** [comment]
It looks like the problem has been solved in 1.27.0.
Thanks.
