### ISSUE TITLE
"Value should be one: false" when using "sap.ui5/flexEnabled": true

### ISSUE THREAD

**Issue by pubmikeb** [SAP/ui5-manifest#7]
When specifying `sap.ui5/flexEnabled`, IDE proposes two possible values: `true` or `false`:
![02_222225](https://user-images.githubusercontent.com/17231333/86405990-9e0bde80-bcb2-11ea-9832-f8ddf7a701bf.png)

If I select `true`, then I have an error «Value should be one: false»:
![02_222407](https://user-images.githubusercontent.com/17231333/86406062-c1cf2480-bcb2-11ea-827b-3b6032de9eed.png)

If I select `false`, then everything is OK.

Please check why it's impossible to specify `true` for `sap.ui5/flexEnabled`.

P.S. Perhaps, leads to https://github.com/SAP/ui5-manifest/issues/8

**Comment by petermuessig** [comment]
Hi @pubmikeb,

can you please provide us the `manifest.json` you used? We would like to understand this a bit more in detail. In the schema there is a selection between flexEnabled false and true which uses different definitions for sub-sections. 

THX and best regards,
Peter

**Comment by pubmikeb** [comment]
Hi @petermuessig,

I've rechecked the manifest, it looks like there was a problem in manifest itself — `targets` section I've used `viewID` instead of `viewId`, once I fixed it, IDE doesn't return any error for `ap.ui5/flexEnabled = true`.

That just proves how it is critical to have a code completion as much as possible.
