### ISSUE TITLE
No error on missing required property in case of "rootView_def_flexEnabled"

### ISSUE THREAD

**Issue by pubmikeb** [SAP/ui5-manifest#8]
`rootView_def_flexEnabled` requires `id` and `viewName` properties.
But if `"flexEnabled": true` (which means the `rootView_def_flexEnabled` scenario) and `rootView` doesn't have an `id` property:
```json
"rootView": {
	"async": true,
	"type": "XML",
	"viewName": "webapp.view.App"
},
```
IDE doesn't return an error:
![02_223211](https://user-images.githubusercontent.com/17231333/86406717-ed064380-bcb3-11ea-8ec0-a897b8c78362.png)

Although `id` is required:
```json
"rootView_def_flexEnabled": {
	"description": "Represents the root view definition when flex is enabled (requires a view id)",
	"type": "object",
	"required": [
		"id",
		"viewName"
	],
}
```

At the same time, if I remove `viewName` — another mandatory property, IDE returns an error:
![02_223228](https://user-images.githubusercontent.com/17231333/86406768-06a78b00-bcb4-11ea-9167-b02b62a20927.png)

Please, check why missing `id` property doesn't lead to a schema error.

P.S. Perhaps, related to https://github.com/SAP/ui5-manifest/issues/7

**Comment by petermuessig** [comment]
Hi @pubmikeb,

we will take a look into the issue - I am sure we validated that in the past - maybe this check is broken.

THX and best regards,
Peter

**Comment by pubmikeb** [comment]
Hi @petermuessig,
is there any roadmap for fixing this ticket?

**Comment by petermuessig** [comment]
Hi @pubmikeb ,

Big Sorry for the long delay! I will follow up on this next Monday with the responsible developers. 

Best regards,
Peter

**Comment by petermuessig** [comment]
Hi @pubmikeb ,

I tried to reproduce this issue here - but it seems to work properly:
![image](https://user-images.githubusercontent.com/1589419/91988045-1af91a00-ed2f-11ea-8aa2-a69e0a273669.png)

If I remove the id property and flexEnabled is true the issue is properly displayed.

Can you please re-check?

Best regards,
Peter

**Comment by pubmikeb** [comment]
I've checked it on an updated schema, it looks like I can't reproduce the issue anymore, therefore, I close the ticket.
